/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cssd.form;

/**
 *
 * @author NESAS
 */
public class frmGudang extends javax.swing.JFrame {

    /**
     * Creates new form frmGudang
     */
    public frmGudang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlNav = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlSteril = new javax.swing.JPanel();
        pnlGudang = new javax.swing.JPanel();
        pnlSetAlat = new javax.swing.JPanel();
        pnlDipinjam = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnlNav.setBackground(new java.awt.Color(225, 241, 221));

        jButton2.setBackground(new java.awt.Color(225, 241, 221));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(118, 97, 97));
        jButton2.setText("STOK STRERIL");
        jButton2.setBorder(null);

        jButton1.setBackground(new java.awt.Color(225, 241, 221));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(118, 97, 97));
        jButton1.setText("STOK GUDANG");
        jButton1.setBorder(null);

        jButton3.setBackground(new java.awt.Color(225, 241, 221));
        jButton3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(118, 97, 97));
        jButton3.setText("LIST SET ALAT");
        jButton3.setBorder(null);

        jButton4.setBackground(new java.awt.Color(225, 241, 221));
        jButton4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(118, 97, 97));
        jButton4.setText("ALAT DIPINJAM");
        jButton4.setBorder(null);

        javax.swing.GroupLayout pnlNavLayout = new javax.swing.GroupLayout(pnlNav);
        pnlNav.setLayout(pnlNavLayout);
        pnlNavLayout.setHorizontalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        pnlNavLayout.setVerticalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(33, 33, 33))
        );

        jSplitPane1.setLeftComponent(pnlNav);

        pnlCards.setBackground(new java.awt.Color(135, 167, 179));
        pnlCards.setLayout(new java.awt.CardLayout());

        pnlSteril.setBackground(new java.awt.Color(135, 167, 179));

        javax.swing.GroupLayout pnlSterilLayout = new javax.swing.GroupLayout(pnlSteril);
        pnlSteril.setLayout(pnlSterilLayout);
        pnlSterilLayout.setHorizontalGroup(
            pnlSterilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        pnlSterilLayout.setVerticalGroup(
            pnlSterilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        pnlCards.add(pnlSteril, "card2");

        pnlGudang.setBackground(new java.awt.Color(135, 167, 179));

        javax.swing.GroupLayout pnlGudangLayout = new javax.swing.GroupLayout(pnlGudang);
        pnlGudang.setLayout(pnlGudangLayout);
        pnlGudangLayout.setHorizontalGroup(
            pnlGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        pnlGudangLayout.setVerticalGroup(
            pnlGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        pnlCards.add(pnlGudang, "card2");

        pnlSetAlat.setBackground(new java.awt.Color(135, 167, 179));

        javax.swing.GroupLayout pnlSetAlatLayout = new javax.swing.GroupLayout(pnlSetAlat);
        pnlSetAlat.setLayout(pnlSetAlatLayout);
        pnlSetAlatLayout.setHorizontalGroup(
            pnlSetAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        pnlSetAlatLayout.setVerticalGroup(
            pnlSetAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        pnlCards.add(pnlSetAlat, "card2");

        pnlDipinjam.setBackground(new java.awt.Color(135, 167, 179));

        javax.swing.GroupLayout pnlDipinjamLayout = new javax.swing.GroupLayout(pnlDipinjam);
        pnlDipinjam.setLayout(pnlDipinjamLayout);
        pnlDipinjamLayout.setHorizontalGroup(
            pnlDipinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        pnlDipinjamLayout.setVerticalGroup(
            pnlDipinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        pnlCards.add(pnlDipinjam, "card2");

        jSplitPane1.setRightComponent(pnlCards);

        getContentPane().add(jSplitPane1, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlDipinjam;
    private javax.swing.JPanel pnlGudang;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JPanel pnlSetAlat;
    private javax.swing.JPanel pnlSteril;
    // End of variables declaration//GEN-END:variables
}
